stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "unix:///var/run/docker.sock"

.before_script_template:
  before_script:
    - apk add --no-cache docker-cli-compose

    # пересоздаём .env
    - rm -f .env
    - echo "FLASK_SECRET_KEY=$FLASK_SECRET_KEY" >> .env
    - echo "LOGIN_USERNAME=$LOGIN_USERNAME" >> .env
    - echo "LOGIN_PASSWORD=$LOGIN_PASSWORD" >> .env
    - echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> .env
    - echo "FLASK_PORT=4017" >> .env
    - echo "FLASK_DEBUG=0" >> .env
    - echo "OSRM_BASE_URL=http://osrm:5000" >> .env

.build_prod_template:
  stage: build
  image: docker:25
  extends: .before_script_template
  script:
    - docker compose build web

.deploy_prod_template:
  stage: deploy
  image: docker:25
  extends: .before_script_template
  script:
    - docker compose up -d web
    - docker image prune -f
build-prod:
  extends: .build_prod_template
  tags: [crm-dev]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-prod:
  extends: .deploy_prod_template
  tags: [crm-dev]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'